### ISSUE TITLE
Add "Avoiding gender bias in reference writing" poster somewhere?

### ISSUE THREAD

**Issue by erictleung** [gender-bias/gender-bias#44]
Although this poster on gender bias already references studies you have referenced in your README, I think this might be a good addition to your repository, somewhere, but not sure where.

> Research from Trix, F & Psenka, C. Exploring the color of glass: Letters of recommendation for female and male medical faculty. Discourse & Society, 2003; and Madera, JM, Hebl, MR, & Martin, RC. Gender and letters of Recommendation for Academia: Agentic and Communal Differences. Journal of Applied Psychology, 2009.

https://csw.arizona.edu/sites/default/files/avoiding_gender_bias_in_letter_of_reference_writing.pdf

H/t from https://twitter.com/pollyp1/status/1040646167305113600 for more discussions

**Comment by j6k4m8** [comment]
Yes!! And there are some similarities with this recent version:
https://aaberhe.files.wordpress.com/2019/03/avoiding-racial-bias-in-reference-writing.pdf

We should definitely have a home for this poster in the repo.

**Comment by molliem** [comment]
Add http://www.rebeccakreitzer.com/bias/ and https://aaberhe.files.wordpress.com/2019/03/avoiding-racial-bias-in-reference-writing.pdf

**Comment by molliem** [comment]
Added all resources!
