### ISSUE TITLE
Web Design

### ISSUE THREAD

**Issue by molliem** [gender-bias/gender-bias#5]
Goal: user-friendly website (www.biascorrect.com) --There is a mock-up linked to the main page.

Components:
- text box for user's to input text that can communicate with python scripts
- side bar for feedback from python
- lots of design help

**Comment by TerrieM** [comment]
Hello, Mollie. I love this project and would like to help with UX design and microcopy. I have a few questions, to help guide my thinking and tone.

1. Who is the primary user for this? The recommendation _writer_ or the recommendation _recipient_?
2. If the primary user is the _writer_, do we anticipate that they are eagerly embracing the opportunity to purge gender bias from their writing?
3. If the recommendation _recipient_ is a secondary user, would it be useful to have an option for the _recipient_ to send an output sample with an invitation link to this tool to the _writer_?

**Comment by molliem** [comment]
Hi TerrieM!  Thank you for your interest and help!  Insightful questions.
1.  Recommendation writer.
2.  I assume that the early adopters will be eager to embrace the opportunity to remove bias.  I think that later users will be more hesitant.  The overall changes to the letters/evaluations should make them stronger as well.  I am hoping this fact will increase buy-in. 
3.  I don't know that recipients will use this tool.  I actually hadn't considered it.  I feel like by the time the recipients are reviewing a letter of recommendation, it is too late.
Thank you for being so thoughtful!!!!

**Comment by jasonclark** [comment]
Hey, Mollie,

I have a baseline stylesheet we could apply to the web page. I would formalize some of the fonts, forms, and link styles. In the interim, we could use it. What do you think?

- jason @jasonclark

**Comment by molliem** [comment]
Great idea! The website could use all the help it can get.

**Comment by GrantRVD** [comment]
Where is the current website hosted? It might be easier to go back and forth between the functionality and design of the website if the repository is used to host both. The bonus is that then Github Pages can also host the site and there are lots of tools out there for auto-generating websites for repositories. One of my favorite is Nikola, which is a static website generator that has a lot of python interfaces.

**Comment by molliem** [comment]
Right now it is hosted at inmotion hosting, but it sounds like your
solution might be better.  I am new to GitHub and wasn't aware of this
functionality.  Thanks for the great twitter shout-out!

**Comment by GrantRVD** [comment]
Anytime! This page does a really good walkthrough of everything to set up a basic page. Just make sure to click "Project Site" near the beginning. It's easy to build on the sites later. There are several ways to make the website work, but the way that probably works best for this project right now is to make a `/docs` subdirectory and modify the settings so GitHub uses that to deploy the site. It even helps you set-up so your custom URL redirects to it.

https://pages.github.com/

**Comment by molliem** [comment]
Thanks so much!  I'll look through it!

**Comment by jamesacklin** [comment]
I would be happy to implement a simple front-end for this, as long as it doesn't stand in the way of other design goals.

**Comment by j6k4m8** [comment]
@trallard :+1: !! What sort of web app are you thinking?

**Comment by trallard** [comment]
Since the whole thing is done using Python I could engineer something using Django or Flask. 

This would allow for better integration of the backend and the front-end

**Comment by molliem** [comment]
Sounds fantastic!  We have it set up to return the reports once generated, but that is the only part that is currently functional.

**Comment by j6k4m8** [comment]
@trallard I'd vote for Flask, if no one else has strong opinions :)

As for front-end, do you have thoughts on React / other frameworks? 

Related, I started looking around at possible ways to render text-highlights. [Markjs](https://markjs.io/) looks nice — I'd be happy to help write some of this (either server or web) if you'd like help!

**Comment by trallard** [comment]
I have no strong feelings regarding front-end (so open to opinions). 

I can focus on the back-end and if you'd like to help with the front-end @j6k4m8 it would be awesome

Also I have not had a look at Markjs but. I will make sure to check it out .

I

**Comment by j6k4m8** [comment]
@TerrieM and @trallard — take a look here for Vue-based front-end. Curious to hear your thoughts! https://github.com/gender-bias/reading-for-genderbias-web

That page is fully serverless and relies upon the flask API server that now lives in this repo:
https://github.com/molliem/gender-bias/blob/master/bin/genderbias-server

**Comment by j6k4m8** [comment]
Closing this since all of our web development is moving to [this repo](https://github.com/gender-bias/gender-bias-web). Hope to see you there! 🎉
