### ISSUE TITLE
Provide usage instructions in the README

### ISSUE THREAD

**Issue by alexwlchan** [gender-bias/gender-bias#51]
Steps to reproduce:

1. Somebody sends me a link to the GitHub repo
2. I started reading the README. A tool for reducing gender bias in my writing, sounds great! I really want to use this tool. I wonder how I use it?
3. I read some more of the README. Okay, I’m sure they’ll explain how to use it soon.
4. Oh, I finished the end of the references. But I’m still not sure how to actually use this tool, even though I really want to!
5. \*sad panda face*

Searching around, it looks like I can get a hosted version of this tool at <http://biascorrect.com> – is that the only way to run it?

A link to that page in the README would make it much easier for somebody who lands on the GitHub repo first.

**Comment by j6k4m8** [comment]
Hey @alexwlchan — thank you so much for bringing this to our attention!

This repo is still very much a work-in-progress, and so while the code is (mostly) tested and (mostly) stable, there have been some pretty hefty changes that altered the way the tool was used. Hence the (semi-deliberate) omission!

I've added some usage documentation to the README in #52; if this is a project you're excited about (and I'm excited to hear that it seems to be!!) we'd love to have your help, whether in coding or just in sanity-checking our documentation next time we leave something important out 😎 

Hopefully the new docs get you started; keep in mind that we're still ramping up, so we're getting more false-positives / false-negatives than we'd like. If you encounter something that doesn't make sense, please let us know here!

Thanks again, from the whole team :)

**Comment by j6k4m8** [comment]
(PS: We're working to get biascorrect.com up and running; right now, it's a roll-your-own type of deal, using the CLI tool / REST API detailed in those docs)
