### ISSUE TITLE
Incorporate new article - Madera, et al. (2019) on "Raising doubt"

### ISSUE THREAD

**Issue by ProfJanetDavis** [gender-bias/gender-bias#58]
This recent paper should appear in the README under "Raise Doubt". See also #10.

Madera, J. M., Hebl, M. R., Dial, H., Martin, R., & Valian, V. (2019). Raising doubt in letters of recommendation for academia: gender differences and their impact. Journal of Business and Psychology, 34(3), 287-303.
http://link.springer.com/10.1007/s10869-018-9541-1

**Comment by j6k4m8** [comment]
Just added this, thank you!
