### ISSUE TITLE
Domain biascorrect.com has expired

### ISSUE THREAD

**Issue by ProfJanetDavis** [gender-bias/gender-bias#59]
I was trying to find the mockup that @molliem created two years ago, and finally found the links in [`web.html`](https://github.com/gender-bias/gender-bias/blob/master/web.html). I tried to follow these links and discovered that the domain name [`biascorrect.com`](http://biascorrect.com) has expired. 

Either the domain should be renewed, or references should be removed and ideally replaced with links to a live web site. In particular, it might be really helpful if my team could see/use the mockup that @molliem made. Thanks!

**Comment by j6k4m8** [comment]
Yes! The host for that website+domain was unfortunately doing some kinda shady things. We now own biascorrect.org and are migrating references slowly! (I'll share more details for deploying to that site privately.)

**Comment by j6k4m8** [comment]
I believe the mockup that was hosted there is [the contents of the `public_html` directory](https://github.com/gender-bias/gender-bias/commit/c8e94a329b930675b592b4828b954a0774a3e67b) in this repo!

**Comment by ProfJanetDavis** [comment]
Awesome, thanks @j6k4m8! I'll make sure we're in touch when we're getting close to having something to deploy.

**Comment by j6k4m8** [comment]
We're now live at [biascorrect.org](https://biascorrect.org)! Shiny new URL :)
