### ISSUE TITLE
Set up cloud-based API server

### ISSUE THREAD

**Issue by ProfJanetDavis** [gender-bias/gender-bias#63]
@j6k4m8 has a plan for this! We need a stable, public backend server to [deploy the web interface](https://github.com/gender-bias/reading-for-genderbias-web/issues/13).

This is a [project](https://github.com/gender-bias/gender-bias/projects/2)!

We tentatively plan to deploy the software as-is to a VM on AWS, deferring the transition to `spacy` and AWS Lambda for later issues.

Plan (16 points):
- [x] Make an AWS account for GLAM-lab and share info with the team (@ProfJanetDavis)
- [ ] Find/do a tutorial on AWS VM-based server deployment (2 dev * 2 points = 4 points)
- [ ] Install the repo on AWS (@j6k4m8 + 2 dev * 1 point = 2 points)
- [x] Get [Gunicorn](https://gunicorn.org/#deployment) running on AWS (@j6k4m8 + 2 dev * 2 point = 4 points)
- [x] Install and integrate [nginx](https://nginx.org/) (@j6k4m8 + 2 dev * 1 points = 2 points)
- [ ] Create new repo for configuration files and instructions (@j6k4m8 + 2 dev * 2 points = 4 points)
- [ ] PR (0 points)

**Comment by j6k4m8** [comment]
I'm trying to brain-dump [here](https://github.com/gender-bias/gender-bias/projects/2). I'll update/clarify text once I have the first few steps in motion! Happy to do these debug sessions on video-call if anyone is interested in listening in :)

**Comment by ProfJanetDavis** [comment]
Awesome, thanks for moving this along! My schedule is pretty full next week, but I bet some of my students will be interested.

**Comment by j6k4m8** [comment]
It is now possible to [mount a shared filesystem in a Lambda runtime](https://aws.amazon.com/jp/blogs/aws/new-a-shared-file-system-for-your-lambda-functions/), which makes this WAY more approachable (and perhaps obviates the need to remove nltk, though i still think we ought to pick one NLP lib and stick with it...)

More docs on lambda limits [here](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html).

**Comment by ProfJanetDavis** [comment]
**Initial plan for planning:**
We are currently in the research & planning phase: 8 points total
- [x] Meet with Jordan (2 dev * 1 point = 2 points)
- [ ] Create an issue for replacing `nltk`with `spacy`(0 points)
- [ ] Determine which code modules use `nltk` - maybe use `grep`? (2 dev * 1 points = 2 points)
- [x] Read an introduction to `spacy` and/or do a simple tutorial (2 dev * 2 points = 4 points)

**Comment by nidhi2509** [comment]
@ProfJanetDavis I am unable to check this boxes, but so far we have an AWS account, and have installed gunicorn and nginx.

**Comment by ProfJanetDavis** [comment]
Thanks for the update, @nidhi2509! I adjusted our team's permissions on this repository. Can you check the boxes now?

**Comment by ProfJanetDavis** [comment]
@nidhi2509 thinks this is done and I agree! The test will be in completing the implementation of [gender-bias-web#13](https://github.com/gender-bias/gender-bias-web/issues/13).
