### ISSUE TITLE
Improve documentation of how to run the test suite

### ISSUE THREAD

**Issue by ProfJanetDavis** [gender-bias/gender-bias#66]
I can't find any documentation on how to run the automated test suite. This seems like an oversight.

It isn't blocking me. There are enough clues in the source code that I think I can figure out on my own how to run the tests. Once I've done so, I would be happy to write up the documentation. (I'll make notes here on this issue.)

The documentation should go in `CONTRIBUTING.md`. _ETA: There is one line on running tests already there; we agree it's not enough._

We probably also need documentation on how to write new tests, but that should be a separate issue.

This is a good task for a pair. It will involve reading the existing document carefully to decide where this new information fits, perhaps looking at other `README`s for guidance, learning Markdown, and writing the documentation based on notes here. Let's have a different pair do this than the other documentation task, so that everyone can learn. We estimate this is a total of 4 story points.

**Comment by ProfJanetDavis** [comment]
Notes:
- Of course, tests are in the `tests` directory.
- There is a script `run_tests.sh` in the main directory. It calls `pytest` and `pylint`.
- So, those packages need to be installed: 
  - `pip install -U pytest` (see https://docs.pytest.org/en/stable/getting-started.html)
  - `pip install -U pylint` (see https://pypi.org/project/pylint/)
  - Find where `pip` installs libraries on your computer. (See https://stackoverflow.com/questions/35898734/pip-installs-packages-successfully-but-executables-not-found-from-command-line.) On mine, it's `~/Library/Python/3.7`. Then append `/bin` to find the directory to add to your `$PATH`: `~/Library/Python/3.7/bin`.
- Finally! You can execute `./run_tests.sh` at the command line.

**Comment by ProfJanetDavis** [comment]
**NB: A lot of tests fail.** Getting the automated tests in sync with the current source code should be a further issue.

**Comment by ProfJanetDavis** [comment]
To run a single test suite, run
`pytest tests/test_suite.py`

For example, to test only the Publications Detector, run
`pytest tests/test_publication_detector.py`

**Comment by ProfJanetDavis** [comment]
Hey, @j6k4m8, I think I'm ready to write this documentation as soon as I have the time. Should it go in [`CONTRIBUTING.md`](https://github.com/gender-bias/gender-bias/blob/master/CONTRIBUTING.md) or somewhere else?

**Comment by ProfJanetDavis** [comment]
@Life1999 has a local commit she has not pushed yet. @nidhi2509 will get the instructions from her to test them out.

**Comment by j6k4m8** [comment]
Sorry, just saw this! Contrib is a great place for it, or we can start docs in the [Wiki (https://github.com/gender-bias/gender-bias/wiki) (which i think is totally empty right now)

**Comment by ProfJanetDavis** [comment]
Resolved in PR #74
