### ISSUE TITLE
Restore the old Effort vs Accomplishment detector

### ISSUE THREAD

**Issue by ProfJanetDavis** [gender-bias/gender-bias#82]
PR #73 modified the Effort vs Accomplishment detector to identify phrases in which an effort adjective is associated with the candidate, not the writer. This new detector is very precise, but has a high false negative rate relative to the old detector. In particular, it does not detect words such as "willingness" in the sample letters. 

Therefore, we would like to resurrect the old Effort vs Accomplishment detector and run it alongside the new one.

So we'll have two detectors for Effort vs Accomplishment: 

1. The new detector using spacy, which has high precision but poor recall;
2. The old detector using nltk, which has high recall but poor precision.

The code for (1) is already in the master branch of the repository. Let's rename this detector to `effort-precise`.

The code for (2) needs to be resurrected from the last commit in 2018. Let's put it in a new directory `effort-wordlist`.

**Comment by j6k4m8** [comment]
Added this as a byproduct of fixing tests in #83.
