### ISSUE TITLE
Other relevant references and inspirations that could be added

### ISSUE THREAD

**Issue by erictleung** [gender-bias/gender-bias#86]
I came across a number of references and other work that might be relevant to share.

**biasly**
- "Tackling gender bias in text" https://drive.google.com/file/d/1--Gu_mcHssy7KLPePSvNExiOQt8Emmur/view
- https://github.com/k1c/biasly
- Publications https://sites.google.com/view/biaslyai/about/publications?authuser=0

**Gender Bias Calculator**
- "A tool to calculate gender-bias in recommendation letters based on an implementation by Thomas Forth" https://github.com/slowe/genderbias
- Demo https://slowe.github.io/genderbias/

**Comment by molliem** [comment]
Thank you!!! Added these to the readme!
